### ISSUE TITLE
[FEAT]: Add `pre-commit` hook

### ISSUE THREAD

**Issue by adam-grant-hendry** [zanieb/poetry-relax#61]
Could we please add a `pre-commit` hook for this project?

## `.pre-commit-hooks.yaml
```yaml
- id: poetry-relax
  name: poetry-relax
  description: A poetry plugin to relax dependency versions when publishing libraries.
  entry: poetry relax
  language: python
  language_version: python3
  pass_filenames: false
  files: ^pyproject.toml$
```
